// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Vo8hIP_exg8ryuEzJxa2QLxEJPrFaRA',
    appId: '1:621159648287:web:936f17eb19dcfc2bb0d92a',
    messagingSenderId: '621159648287',
    projectId: 'flutter-moviesflix',
    authDomain: 'flutter-moviesflix.firebaseapp.com',
    storageBucket: 'flutter-moviesflix.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3bYyXtp0zOX8pkGatuNhYmGD_6CN5OXQ',
    appId: '1:621159648287:android:f9de6ae45d2ab614b0d92a',
    messagingSenderId: '621159648287',
    projectId: 'flutter-moviesflix',
    storageBucket: 'flutter-moviesflix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ad6-orby-CQtqY_JveUc8w1fSvEboqc',
    appId: '1:621159648287:ios:4944b3e37bc9a4f8b0d92a',
    messagingSenderId: '621159648287',
    projectId: 'flutter-moviesflix',
    storageBucket: 'flutter-moviesflix.appspot.com',
    iosBundleId: 'com.example.flutterMoviesflixApp',
  );
}
